name: Automatic Tagging

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 現在の最新タグを取得
        id: cur_tag_var
        run: |
          git fetch --prune --unshallow
          echo "$(git tag --sort=creatordate | tail -n 1)" > CUR_TAG
          echo ::set-output name=cur_tag::$(cat CUR_TAG)

      - name: リリースタグを設定
        id: set_release_tag
        run: |
          echo "${{ steps.cur_tag_var.outputs.cur_tag }}"
          # タグが存在しない場合、初期リリースとしてv1.0.0.0をセット
          if [[ "${{ steps.cur_tag_var.outputs.cur_tags }}" == '' ]]; thens
            NEW_TAG="v1.0.0.0"
            echo "Initial release: $NEW_TAG"
            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
            exit 0
          fi

          echo "コール"
