name: Automatic Tagging

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 #これがないとcheckoutの利用時にエラーが出る。

      - name: Generate new tag
        id: new_tag
        run: |
          echo "コール"
          # タグが存在するか確認
          if ! git rev-list --tags --max-count=1 2>/dev/null; then
            # タグが存在しない場合
            echo "タグなし"
            LATEST_TAG=""
          else
            # 最新のタグを取得
            echo "タグあり"
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          fi

          # 最新のタグを取得
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)

          echo "Latest tag: $LATEST_TAG"
